### ISSUE TITLE
Unable to install via pip on Python 2.7.11 and Redis 2.10.5

### ISSUE THREAD

**Issue by rdempsey** [nbrochu/requests-respectful#1]
Hello!

I'm unable to install the library. Here's my environment:
- Mac OS X El Capitan 10.11.5
- Python (Anaconda) 2.7.11
- redis 2.10.5

Here's the error I get when running `pip install requests-respectful`:

`$ pip install requests-respectful
Collecting requests-respectful
  Using cached requests-respectful-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kw/2n84gk1s2v5d4_s1p93vdjym0000gp/T/pip-build-LSndMf/requests-respectful/setup.py", line 10, in <module>
        import requests_respectful
      File "/private/var/folders/kw/2n84gk1s2v5d4_s1p93vdjym0000gp/T/pip-build-LSndMf/requests-respectful/requests_respectful/__init__.py", line 15, in <module>
        from .respectful_requester import RespectfulRequester
      File "/private/var/folders/kw/2n84gk1s2v5d4_s1p93vdjym0000gp/T/pip-build-LSndMf/requests-respectful/requests_respectful/respectful_requester.py", line 1, in <module>
        from .globals import default_config, config, redis
      File "/private/var/folders/kw/2n84gk1s2v5d4_s1p93vdjym0000gp/T/pip-build-LSndMf/requests-respectful/requests_respectful/globals.py", line 2, in <module>
        from redis import StrictRedis, ConnectionError
    ImportError: No module named redis`

I appreciate your help with this and look forward to using the library.

**Comment by nbrochu** [comment]
I'm going to create a fresh Anaconda environment and try to replicate this.

**Comment by nbrochu** [comment]
Try installing 0.1.1. I had something messed up in the package file. Sorry about that!

**Comment by rdempsey** [comment]
Works. Thanks!
